version: '3.1'

services:

  postgresql:
    image: postgres:12
    restart: always
    privileged: true
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: 'localhost'
      POSTGRES_USER: 'mask_network'
      POSTGRES_DB: 'datawaves_data'
      POSTGRES_PASSWORD: 'MaskNetW'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/fuzezhong/docker/postgres/data:/var/lib/postgresql/data/pgdata

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8180:8080
