# Local Variables:
# mode: justfile
# End:

set dotenv-load
set export

arch := `uname -m`

# Start peripherals of this server
peri:
	docker-compose -f docker-compose.yml up -d

# Do database migration.
migrate: peri
	cd db-migrate && db-migrate up -v --config database.test.json

clean:
	docker-compose down -v