FROM amazon/aws-sam-cli-build-image-python3.8:latest

LABEL maintainer="Zella Zhong <zella@mask.io>"

COPY requirements.txt .

# postgresql migrate
RUN curl -sL https://rpm.nodesource.com/setup_14.x | bash - && \
    yum -y install nodejs
RUN npm install -g db-migrate
RUN npm install -g db-migrate-pg
RUN pip3 install -r requirements.txt
